local_backend: true

logo_url: /favicon.png

backend:
  name: github
  repo: drtheodor/trying-out-cms
  branch: main
  base_url: https://sveltia-cms-auth.drtheo.workers.dev/

publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'


media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

i18n:
  structure: 'multiple_folders'
  locales: ['en', 'es', 'ar', 'ja', 'zh-cn']
  default_locale: 'en'

collections:
  - name: 'entries'
    label: 'Wiki Entries'
    label_singular: 'Entry'
    folder: 'content/wiki'
    create: true
    path: '{{fields.category}}/{{slug}}'
    extension: md
    i18n: true
    media_folder: ''
    public_folder: ''
    editor:
      preview: true
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Title'
        i18n: true
      - name: 'description'
        widget: 'string'
        label: 'Description'
        i18n: true
      - name: 'lastModified'
        widget: 'datetime'
        label: 'Last Modified'
        required: false
        default: "{{now}}"
        i18n: 'duplicate'
      - name: 'category'
        widget: 'relation'
        collection: 'categories'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: false
        i18n: 'duplicate'
      - name: 'draft'
        widget: 'boolean'
        label: 'Draft'
        default: true
        i18n: 'duplicate'
      - name: 'body'
        widget: 'markdown'
        label: 'Body'
        i18n: true

  - name: categories
    label: Categories
    label_singular: Category
    folder: src/data/categories
    slug: '{{title}}'
    create: true
    i18n: true
    fields:
      - name: title
        widget: string
        label: Title
        i18n: true
      - name: order
        widget: number
        label: Order
        required: false
        value_type: int
        min: -1000
        max: 1000
        step: 1
        default: 0
        i18n: 'duplicate'


        widget: 'markdown'
        label: 'Bio'
        i18n: true
